spring.application.name=LinkMetric


# =========================
# APPLICATION CONFIG
# =========================
server.port=8080

# =========================
# DATABASE CONFIG (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener
spring.datasource.username=root
spring.datasource.password=Golo12@seedhu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

